apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-cart-product
  name: shopping-cart-product-service
  namespace: default
spec:
  ports:
  -  port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    app: shopping-cart-product
  type: LoadBalancer

